### ISSUE TITLE
TestReports.test behaves differently from Pkg.test when called without positional arguments

### ISSUE THREAD

**Issue by bauglir** [JuliaTesting/TestReports.jl#14]
The behavior of `Pkg.test` in Julia v1 is described as:
> Run the tests for package pkg, or for the current project (which thus needs to be a package) if no positional argument is given to Pkg.test.

`TestReports.test` tries to run the tests for all installed packages:
https://github.com/JuliaTesting/TestReports.jl/blob/671ae076c344eb507750d890994fab56445681ca/src/runner.jl#L127

This is in-line with the behavior pre-v1, which was:
> Run the tests for all installed packages ensuring that each package's test dependencies are installed for the duration of the test.

However, this fails because `installed` is not defined. It looks like this may have referred to `Pkg.installed` in the past, but I haven't been able to figure out if this used to work previously (I've tested back to Julia v0.5). `Pkg.installed` still exists in Julia v1, but appears to be deprecated as-of v1.4.

It seems preferable to bring the `TestReports.test` behavior in-line with `Pkg.test` and get rid of the `Pkg.installed` reference altogether.

Perhaps this is part of a bigger PR of bringing the `TestReports.test` API in-line with the `Pkg.test` API? I'm not certain to what extent @mmiller-max intends to tackle that in the context of #10. Seems like this could be mostly orthogonal to that work.

**Comment by mmiller-max** [comment]
Yes this is a very good point.

I think #10 should just be the sandboxing, with a subsequent PR aligning the APIs which could include the keyword arguments `test_fn`, `julia_args` and `test_args` if they're not big enough changes to warrant their own PR(s).

**Comment by bauglir** [comment]
That makes sense, let me know if I can help out with that. The `test` function could probably also use some docstrings while aligning the API :) Perhaps it suffices to refer to `Pkg.test` and only document additional arguments?

I was also wondering whether it'd be possible to get rid of some of the (apparent) duplication between `Pkg.test` and `TestReports.test` at some point, but I'm not deep enough into the codebase of either at the moment to make any clear judgment on that part. Probably also another issue to begin with.

**Comment by mmiller-max** [comment]
> let me know if I can help out with that

Feel free to get the keyword arguments working or add docstrings - they're on my mental list of things that need doing but haven't got around to making the issues yet!

> I was also wondering whether it'd be possible to get rid of some of the (apparent) duplication between `Pkg.test` and `TestReports.test`

My thought was to keep them as similar as possible, partly for familiarity, partly as the `Pkg.test` code is pretty well tested and partly in case there is ever a plan to include the JUnit functionality within `Pkg.test` itself. Where possible, I've tried to reuse functions rather than re-create them here. However this does result in some messy code and duplication as you point out. Please feel free to create an issue and we can discuss further.

**Comment by bauglir** [comment]
I also don't have the mental bandwidth at the moment to turn these into issues, but I'll put it on my personal/mental backlog to create them after JuliaCon 😄 .
