### ISSUE TITLE
Do we need a custom testset type?

### ISSUE THREAD

**Issue by oxinabox** [JuliaTesting/TestReports.jl#2]
Right now the code almost works  on `DefaultTestset`s

The reason it doesn't is that they don't keep `Pass`es in `results`
(Could work around by rewriting a bit to use the recorded counts of passes and thus synthisis the elements)
And because they throw an exception at the end if there were any issues.

Could work around by making the runner scripts use a try catch block.
But idk if that will break being top level for purposes of `using` expressions.

Anyway, something to think about.

**Comment by mmiller-max** [comment]
As we've now added more fields to `ReportingTestSet` I think we can close this issue now!
