### ISSUE TITLE
complexexample fails new releases

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#21]
At least for `v1.5`, the complex example test is the only one that fails in CI. Couple of options:

- Remove the test - but what is it testing that nothing else isn't? That the printing of the xml file for a range of issues doesn't change, and it is reasonable that this changes with the version of Julia being used.
- Enforce the version to be v1.4 only, rather than v1.4 or greater, and then update every time the v1 tag on CI is updated
- Add an option to ignore the stack trace when recording errors/fails, as it is the stack trace that differs rather than the fail/error itself (this could produce clearer XMLs, not sure what the standard level of detail is)

Would be good to fix this to see whether upcoming releases will break the package.

**Comment by oxinabox** [comment]
It seems like we should just strip out the stack traces before looking at the reference files.
Like we already strip a bunch of other stuff:
https://github.com/JuliaTesting/TestReports.jl/blob/342b4e6cc33f9cdc280ec993f28d8e51e618fb08/test/runtests.jl#L10-L18

> what is it testing that nothing else isn't?

It runs this file:
https://github.com/JuliaTesting/TestReports.jl/blob/master/test/example_normaltestsets.jl

It has a whole bunch of things that could come out weird.
It has
 -  3x deep nested testset
 - test-cases that are on the same level as some test sets
 - `@test_broken`

Probably some other stuff.
its just the catch all to make sure things actually work.

**Comment by mmiller-max** [comment]
> It seems like we should just strip out the stack traces before looking at the reference files.

Yep good idea, makes sense. Definitely a useful test to keep in.
