### ISSUE TITLE
Add timing information

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#49]
Both `testcase` and `testsuite` attributes require a `time` attribute, and `testsuite` elements additionally require a `timestamp` attribute.

I don't think it will be possible (without it being super complicated) to time individual testcases (`@test`, `@test_throws` etc)

**Comment by oxinabox** [comment]
We might be able to time indivual testcastes by:
 - Given each ReferenceTestSuite a `last_record_time` set to `now()` when created, and whenever `record` is called.
 - each `@test` will call `record` whenever it completes. So we just assign all time between `last_record_time` and it's calling `record` to that testcase

https://github.com/JuliaTesting/TestReports.jl/blob/1aa41e1f0b0baed4ad301c18731ad100aa3e2df7/src/testsets.jl#L31

**Comment by mmiller-max** [comment]
Oh yeah that's a great idea, nice one. I'll give it a go on the branch I'm working on
