### ISSUE TITLE
Speed up Tests

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#51]
Currently the tests take 42 minutes to run (total). A lot of that is in adding and removing of packages/updating manifests.

TODO: run some benchmarks and see where the time is taken and then reduce

**Comment by oxinabox** [comment]
:woah, that is ridiculously slow

**Comment by mmiller-max** [comment]
- The tests activate each test package, when they don't need to
- Set constant so registry doesn't keep updating/use DEPOT_PATH properly
