### ISSUE TITLE
Tests fail in PkgEval and when testing installed Package

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#53]
```Julia
using Pkg
Pkg.add("TestReports")
Pkg.test("TestReports)
...
Report generation: Error During Test at /Users/user/.julia/packages/TestReports/eCRre/test/recordproperty.jl:53
  Got exception outside of a @test
  SystemError: opening file "/var/folders/29/f6ksj93n5dz5zwdbz89rt9kh95rtb6/T/jl_3bzX58/TestsWithProperties/Project.toml": Permission denied
```

Editing of project file of test packages fails due to write permissions.

**Comment by mmiller-max** [comment]
So the error above can be easily fixed by a `chmod`, but this exposed a much bigger error which makes me wonder how this package is even being used...

The following command:
```cmd
 $ julia -e 'using Pkg; Pkg.add("TestReports"); Pkg.add("Example"); using TestReports; TestReports.test("Example")'
```
Results in this error:
```Julia
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
[ Info: Testing Example
ERROR: LoadError: ArgumentError: Package EzXML [8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at ./loading.jl:999
 [2] require(::Base.PkgId) at ./loading.jl:928
 [3] require(::Module, ::Symbol) at ./loading.jl:923
 [4] include(::Function, ::Module, ::String) at ./Base.jl:380
 [5] include(::Module, ::String) at ./Base.jl:368
 [6] top-level scope at none:2
 [7] eval at ./boot.jl:331 [inlined]
 [8] eval(::Expr) at ./client.jl:467
 [9] top-level scope at ./none:3
in expression starting at /Users/malmiller/repos/TestReports.jl/src/TestReports.jl:5
ERROR: Failed to precompile TestReports [dcd651b4-b50a-5b6b-8f22-87e9f253a252] to /Users/malmiller/.julia/compiled/v1.5/TestReports/Yu2WM_MGWSo.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
ERROR: TestReports failed to generate the report.
See error log above.
```
If I run the same command but ensure that the directory of the installed `TestReports` has a `Manifest`, it all works fine.

The problem seems to come down to this line in the runner code:
https://github.com/JuliaTesting/TestReports.jl/blob/cc146819be746274c286e544ff3ab540bd1226e6/src/runner.jl#L34
If `testreportsdir` contains a `Manifest`, the dependencies (`EzXML`) gets loaded into the test environment. If there isn't a `Manifest` this doesn't happen.

 I'm pretty stumped as to why this is happening.

We can work round it, by either adding a `deps/build.jl` which forces the creation of a `Manifest`, or by running `Pkg.add("TestReports")` at the start of the `sandbox`, but I think this is worth understanding?

**Comment by fredrikekre** [comment]
(From discussing on slack)
This line https://github.com/JuliaTesting/TestReports.jl/blob/cc146819be746274c286e544ff3ab540bd1226e6/src/runner.jl#L34
needs to be replaced with something like

1. collect all deps of TestReports from the environment the user uses,
2. create a new tmp env with those entries,
3. push that *last* to `LOAD_PATH`,

I think.

**Comment by mmiller-max** [comment]
In PR #64 I've created a new environment which contains both `TestReports` and `Test` as dependencies as both of these are used in the runner code. `TestReports` is a developed version, ensuring that the correct version is used.
