### ISSUE TITLE
Missing/incorrect attributes in report

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#56]
- `testsuites` element does not need `id` attribute or `name` attributes and they currently default to "_id_" and "" anyway. Other attributes are technically not needed but contain useful information so may as well keep for now
- `testsuite` `id` attribute should start at zero and increment upwards for each one
- `testsuite` element should have `hostname` attribute

Reference: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by oxinabox** [comment]
When I wrote these I failed to find a schema and had to work off a small number of examples

**Comment by mmiller-max** [comment]
Yeah it's pretty hard to find a single source of truth for it! I thought that having additional fields can't hurt and means they're there if another program is expecting them
