### ISSUE TITLE
Pass information is now available! 🎆 

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#77]
As of 1.7:

```Julia
julia> a = 1
1

julia> @test a == 1
Test Passed
  Expression: a == 1
   Evaluated: 1 == 1
```

So we can now include this information in test reports.

**Comment by toollu** [comment]
Any plan/guidance to implement this? Would be lovely to have.

**Comment by mmiller-max** [comment]
Thanks for the reminder, I might be able to take a look at this later in the week. If you'd like to give it a go, this method needs updating (for 1.7 and later) to use the information in the `Pass` object

https://github.com/JuliaTesting/TestReports.jl/blob/e170f9deecf2dcecc70a60daad63d89307f747e5/src/to_xml.jl#L221-L224
